// Input 0
function id(b){return document.getElementById(b)}function cElem(b){return document.getElementsByClassName(b)}
function checkBox(b){var h=document.getElementsByClassName(b.check),d=document.querySelectorAll("."+b.input+" .to_flex"),e=document.getElementById("preview_css_container").querySelector("div.scroll"),f=document.getElementById("preview_css_items").querySelector("div.scroll");document.getElementById("flex_demo");for(var k=0;k<h.length;k++){var m=function(){var a=this.querySelector("span"),l=this.parentNode.querySelectorAll("span");if("checkbox_item_nochecked"===a.classList.value){for(var d=0;d<l.length;d++)l[d].classList.remove("checkbox_item_checked"),
l[d].classList.add("checkbox_item_nochecked");a.classList.remove("checkbox_item_nochecked");a.classList.add("checkbox_item_checked");a.setAttribute("data-check","checked");b.css[this.parentNode.querySelector("h1").textContent]=this.querySelector("p").textContent;this.parentNode.getElementsByClassName("items")[0].style.backgroundColor="#4B57C7"}else a.classList.remove("checkbox_item_checked"),a.classList.add("checkbox_item_nochecked"),a.setAttribute("data-check","nochecked"),delete b.css[this.parentNode.querySelector("h1").textContent],
this.parentNode.getElementsByClassName("items")[0].style.backgroundColor="#CC4656";f.innerHTML=null;e.innerHTML=null;for(var c in flexbox)if("display"==c||"flex-direction"==c||"justify-content"==c||"align-content"==c||"align-items"==c||"flex-wrap"==c)e.innerHTML+=c+": "+flexbox[c]+";\n","display"==c&&(id("flex_demo").style.display=flexbox[c]),"flex-direction"==c&&(id("flex_demo").style.flexDirection=flexbox[c]),"justify-content"==c&&(id("flex_demo").style.justifyContent=flexbox[c]),"align-content"==
c&&(id("flex_demo").style.webkitAlignContent=flexbox[c],id("flex_demo").style.alignContent=flexbox[c]),"align-items"==c&&(id("flex_demo").style.alignItems=flexbox[c]),"flex-wrap"==c&&(id("flex_demo").style.flexWrap=flexbox[c]);else for(f.innerHTML="flex-basis"==c?f.innerHTML+(c+": "+flexbox[c]+"px;\n"):f.innerHTML+(c+": "+flexbox[c]+";\n"),a=0;a<cElem("flex_elem_demo").length;a++)"flex-basis"==c&&(cElem("flex_elem_demo")[a].style.flexBasis=flexbox[c]+"px"),"flex-grow"==c&&(cElem("flex_elem_demo")[a].style.flexGrow=
flexbox[c]),"flex-shrink"==c&&(cElem("flex_elem_demo")[a].style.flexShrink=flexbox[c]),"align-self"==c&&(cElem("flex_elem_demo")[a].style.alignSelf=flexbox[c]),"order"==c&&(cElem("flex_elem_demo")[a].style.order=flexbox[c])},g=document.createElement("span");g.classList.add("checkbox_item_nochecked");h[k].appendChild(g);for(g=0;g<d.length;g++)d[g].addEventListener("keyup",function(){this.value?(b.css[this.parentNode.parentNode.parentNode.querySelector("h1").textContent]=this.value,this.parentNode.parentNode.parentNode.getElementsByClassName("items")[0].style.backgroundColor=
"#4B57C7"):(delete b.css[this.parentNode.parentNode.parentNode.querySelector("h1").textContent],this.parentNode.parentNode.parentNode.getElementsByClassName("items")[0].style.backgroundColor="#CC4656");f.innerHTML=null;e.innerHTML=null;for(var a in flexbox)if("display"==a||"flex-direction"==a||"justify-content"==a||"align-content"==a||"align-items"==a||"flex-wrap"==a)e.innerHTML+=a+": "+flexbox[a]+";\n","display"==a&&(id("flex_demo").style.display=flexbox[a]),"flex-direction"==a&&(id("flex_demo").style.flexDirection=
flexbox[a]),"justify-content"==a&&(id("flex_demo").style.justifyContent=flexbox[a]),"align-content"==a&&(id("flex_demo").style.webkitAlignContent=flexbox[a],id("flex_demo").style.alignContent=flexbox[a]),"align-items"==a&&(id("flex_demo").style.alignItems=flexbox[a]),"flex-wrap"==a&&(id("flex_demo").style.flexWrap=flexbox[a]);else{f.innerHTML="flex-basis"==a?f.innerHTML+(a+": "+flexbox[a]+"px;\n"):f.innerHTML+(a+": "+flexbox[a]+";\n");for(var d=0;d<cElem("flex_elem_demo").length;d++)"flex-basis"==
a&&(cElem("flex_elem_demo")[d].style.flexBasis=flexbox[a]+"px"),"flex-grow"==a&&(cElem("flex_elem_demo")[d].style.flexGrow=flexbox[a]),"flex-shrink"==a&&(cElem("flex_elem_demo")[d].style.flexShrink=flexbox[a]),"align-self"==a&&(cElem("flex_elem_demo")[d].style.alignSelf=flexbox[a]),"order"==a&&(cElem("flex_elem_demo")[d].style.order=flexbox[a])}});b.bind&&void 0!=b.bind&&" "!=b.bind&&0!=b.bind&&null!=b.bind?document.getElementsByClassName(b.bind)[k].addEventListener(b.listener,m):h[k].addEventListener(b.listener,
m)}}var flexbox={},element={};checkBox({check:"checkbox",listener:"click",bind:"ch_i",css:flexbox,input:"items"});function wh(b){return+(window.innerHeight*b/100)}id("flex_elements").style.height=wh(100)+"px";id("body").style.height=wh(100)+"px";id("preview_content").style.height=wh(70)+"px";id("preview_css_container").style.height=wh(30)+"px";id("preview_css_items").style.height=wh(30)+"px";
window.addEventListener("resize",function(){id("flex_elements").style.height=wh(100)+"px";id("body").style.height=wh(100)+"px";id("preview_content").style.height=wh(70)+"px";id("preview_css_container").style.height=wh(30)+"px";id("preview_css_items").style.height=wh(30)+"px"});
function createDemos(){function b(b,d){return cElem("others")[b].querySelector(d)}this.querySelector("div").id="load";cElem("posa")[0].style.display="block";document.querySelector("#preview_content > div").style.backgroundColor="#fff";document.querySelector("#ph").style.display="none";setTimeout(function(){cElem("loadergenb")[0].querySelector("div").removeAttribute("id");cElem("posa")[0].style.display="none"},1800);id("flex_demo").innerHTML=null;var h=b(5,"input").value&&"number"==typeof parseInt(b(5,
"input").value)?b(5,"input").value:10;for(var d=0;d<h;d++){var e=document.createElement("div");e.classList.add("flex_elem_demo");e.textContent=b(4,"input").value;b(0,"input").value?(e.style.minWidth=b(0,"input").value,element["min-width"]=b(0,"input").value):(e.style.minWidth="100px",element["min-width"]="100px");b(1,"input").value?(e.style.minHeight=b(1,"input").value,element["min-height"]=b(1,"input").value):(e.style.minHeight="100px",element["min-height"]="100px");b(2,"input").value?(e.style.margin=
b(2,"input").value,element.margin=b(2,"input").value):(e.style.margin="5px",element.margin="5px");b(3,"input").value?(e.style.padding=b(3,"input").value,element.padding=b(3,"input").value):(e.style.padding="30px0 0 0",element.padding="30px0 0 0");id("flex_demo").appendChild(e)}if(!b(4,"input").value||"nums"==b(4,"input").value)for(d=0;d<cElem("flex_elem_demo").length;d++)cElem("flex_elem_demo")[d].innerText=d+1}id("genb").addEventListener("click",createDemos);